---

- hosts: all
  roles: [common]

- hosts: gallery
  roles: [gallery]
  vars:
    gallery_https: true

- hosts: pycons
  roles: [pelican]
  vars:
    pelican_user: pycon2010
    pelican_https: true
    pelican_domain: 2010.pycon.fr
    pelican_repo: https://github.com/AFPy/pyconfr_2010
    pelican_path_in_repo: 2010/
    pelican_home: "/srv/{{ pelican_user }}/"

- hosts: pycons
  roles: [pelican]
  vars:
    pelican_user: pycon2011
    pelican_https: true
    pelican_domain: 2011.pycon.fr
    pelican_repo: https://github.com/AFPy/pyconfr_2010
    pelican_path_in_repo: 2011/
    pelican_home: "/srv/{{ pelican_user }}/"

- hosts: pycons
  roles: [static]
  vars:
    static_user: pycon2012
    static_https: true
    static_domain: 2012.pycon.fr
    static_repo: https://github.com/AFPy/pyconfr_2012
