---

- hosts: webservers
  vars:
    public_deploy_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbgxOufHY7SxQrJNTlHmye+xeNHBA1O5SGtGhGeOVZM"
  tasks:
    - name: Basic setup
      include_role: name=common

    - name: Setup PyConFr 2010
      include_role: name=julienpalard.nginx
      vars:
        nginx_owner: pyconfr2010
        nginx_domain: 2010.pycon.fr
        nginx_certificates: [2010.pycon.fr]
        nginx_path: /var/www/2010.pycon.fr/

    - name: Setup PyConFr 2011
      include_role: name=julienpalard.nginx
      vars:
        nginx_owner: pyconfr2011
        nginx_domain: 2011.pycon.fr
        nginx_certificates: [2011.pycon.fr]
        nginx_path: /var/www/2011.pycon.fr/

    - name: Setup PyConFr 2012
      include_role: name=julienpalard.nginx
      vars:
        nginx_owner: pyconfr2012
        nginx_domain: 2012.pycon.fr
        nginx_certificates: [2012.pycon.fr]
        nginx_path: /var/www/2012.pycon.fr/

    - name: Setup sigal of paullaroid.pycon.fr
      include_role: name=julienpalard.nginx
      vars:
        nginx_owner: paullaroid
        nginx_domain: paullaroid.pycon.fr
        nginx_certificates: [paullaroid.pycon.fr]
        nginx_path: /var/www/paullaroid.pycon.fr/
