---

- hosts: webservers
  vars:
    public_deploy_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbgxOufHY7SxQrJNTlHmye+xeNHBA1O5SGtGhGeOVZM"
  tasks:
    - name: Basic setup
      include_role: name=common

    - name: Setup PyConFr 2010
      include_role: name=julienpalard.static_website
      vars:
        owner: pycon2010
        domain: 2010.pycon.fr
        path: /var/www/2010.pycon.fr/

    - name: Setup PyConFr 2011
      include_role: name=julienpalard.static_website
      vars:
        owner: pycon2011
        domain: 2011.pycon.fr
        path: /var/www/2011.pycon.fr/

    - name: Setup PyConFr 2012
      include_role: name=julienpalard.static_website
      vars:
        owner: pycon2012
        domain: 2012.pycon.fr
        path: /var/www/2012.pycon.fr/

    - name: Setup sigal of paullaroid.pycon.fr
      include_role: name=julienpalard.static_website
      vars:
        owner: paullaroid
        domain: paullaroid.pycon.fr
        path: /var/www/paullaroid.pycon.fr/
