---

- hosts: pycons
  tasks:
    - name: Basic setup
      include_role: name=common

    - name: Setup PyCon Fr 2010
      include_role: name=pelican
      vars:
        pelican_user: pycon2010
        pelican_https: true
        pelican_domain: 2010.pycon.fr
        pelican_repo: https://github.com/AFPy/pyconfr_2010
        pelican_path_in_repo: 2010/
        pelican_home: "/srv/{{ pelican_user }}/"

    - name: Setup PyConFr 2011
      include_role: name=pelican
      vars:
        pelican_user: pycon2011
        pelican_https: true
        pelican_domain: 2011.pycon.fr
        pelican_repo: https://github.com/AFPy/pyconfr_2010
        pelican_path_in_repo: 2011/
        pelican_home: "/srv/{{ pelican_user }}/"

    - name: Setup PyConFr 2012
      include_role: name=static
      vars:
        static_user: pycon2012
        static_https: true
        static_domain: 2012.pycon.fr
        static_repo: https://github.com/AFPy/pyconfr_2012

- hosts: gallery
  tasks:
    - name: Setup sigal of paullaroid.pycon.fr
      include_role: name=gallery
      vars:
        gallery_https: true
        gallery_user: gallery
        gallery_domain: paullaroid.pycon.fr
        gallery_repo: https://github.com/AFPy/pycon-fr-gallery.git
        gallery_home: /srv/gallery/
