---

- import_playbook: common.yml
- import_playbook: pycon.fr.yml
- import_playbook: afpy.org.yml
# - import_playbook: passbolt.yml  # See https://github.com/laxathom/ansible-role-passbolt/issues/15
- import_playbook: backup.yml
