---

- name: Create rsnapshot SSH key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_rsa_rsnapshot_{{ rsnapshot_name }}"
    ssh_key_comment: "rsnapshot {{ rsnapshot_name }} on {{ inventory_hostname }}"


- name: Fetch rsnapshot ssh public key
  slurp:
    src: "/root/.ssh/id_rsa_rsnapshot_{{ rsnapshot_name }}.pub"
  register: rsnapshot_ssh_pub_key

- name: Propagate rsnapshot ssh public key
  authorized_key:
    user: root
    key: "{{ rsnapshot_ssh_pub_key.content | b64decode | trim }}"
    key_options: "no-pty,no-agent-forwarding,no-X11-forwarding,no-port-forwarding"
    state: present
  delegate_to: "{{ item }}"
  loop: "{{ rsnapshotted_hosts }}"
  loop_control:
    label: "Propagate public key to {{ item }}"

- name: Configure rsnapshot
  template:
    src: rsnapshot.conf.j2
    dest: "/etc/rsnapshot_{{ rsnapshot_name }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Configure rsnapshot cron
  template:
    src: rsnapshot.cron.j2
    dest: "/etc/cron.d/rsnapshot_{{ rsnapshot_name }}"
    owner: root
    group: root
    mode: 0644
