---

- include: setup.yml
  tags: setup

- include: config.yml
  tags: config

- include: backup.yml
  tags: backup

- name: Start gitea
  service: name=gitea enabled=yes state=started daemon_reload=yes
