---

- name: Remove /etc/apt/sources.list (May contain cdroms…)
  file:
    path: /etc/apt/sources.list
    state: absent

- name: Add stretch repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
   - "deb http://ftp.fr.debian.org/debian/ stretch main non-free contrib"
   - "deb http://security.debian.org/ stretch/updates main contrib non-free"
   - "deb http://ftp.fr.debian.org/debian stretch-backports main"
   - "deb http://ftp.fr.debian.org/debian stretch-updates main"

- name: Update via apt
  apt: update_cache=yes

- name: apt-get some packages
  apt:
    state: present
    name:
      - aptitude
      - ntp
      - rsync
      - fail2ban
      - emacs25-nox
      - vim-nox
      - htop
      - ncdu
      - tcpdump
      - python3
      - python3-pip
      - python3-dev
      - python3-venv
      - python3-setuptools
      - python3-wheel
      - sudo

- name: Set some authorized keys
  authorized_key: user=root key="{{item}}"
  with_items: "{{ authorized_keys }}"

- name: Drop mlocate or locate
  apt:
    name: ["mlocate", "locate"]
    state: absent

- name: Drop all Python packages installed globall (Please use venvs)
  file:
    path: "/usr/local/lib/python{{ item }}"
    state: absent
  with_items:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - 3.7
