---

- block:
  - name: Configure hostname
    hostname:
      name: "{{ inventory_hostname_short }}"

  - package: name=nftables state=present

  - service: name=nftables enabled=yes state=started daemon_reload=yes

  - copy:
      content: |
        #!/usr/sbin/nft -f

        flush ruleset

        table inet filter {
            chain input {
                type filter hook input priority 0;
                iif lo accept
                ct state established,related accept
                tcp dport { ssh, http, https, smtp } ct state new accept
                counter drop
            }
        }

      dest: /etc/nftables.conf
      owner: root
      group: root
      mode: 0755
    notify: reload nftables

  - name: Remove /etc/apt/sources.list (May contain cdroms…)
    file:
      path: /etc/apt/sources.list
      state: absent

  - name: Setup apt source list for buster
    copy:
      dest: /etc/apt/sources.list.d/debian.list
      content: |
        deb https://deb.debian.org/debian buster main non-free contrib
        deb http://security.debian.org/debian-security buster/updates main contrib non-free
        deb https://deb.debian.org/debian buster-updates main

  - name: Update via apt
    apt: update_cache=yes

  - name: Install some usefull packages
    apt:
      state: present
      name:
        - aptitude
        - ntp
        - rsync
        - fail2ban
        - emacs25-nox
        - vim-nox
        - htop
        - ncdu
        - tcpdump
        - python3
        - python3-pip
        - python3-dev
        - python3-venv
        - python3-setuptools
        - python3-wheel
        - sudo

  - name: Set some authorized keys
    authorized_key: user=root key="{{item}}"
    with_items: "{{ authorized_keys }}"

  - name: Ensure mlocate and locate are not installed
    apt:
      name: ["mlocate", "locate"]
      state: absent

  tags: common
