---

- block:
  - name: Configure hostname
    hostname:
      name: "{{ inventory_hostname_short }}"

  - package: name=nftables state=present

  - service: name=nftables enabled=yes state=started daemon_reload=yes

  - copy:
      content: |
        #!/usr/sbin/nft -f

        flush ruleset

        table inet filter {
            chain input {
                type filter hook input priority 0;
                iif lo accept
                ct state established,related accept
                tcp dport { ssh, http, https, smtp, imap2, imaps} ct state new accept
                counter drop
            }
        }

      dest: /etc/nftables.conf
      owner: root
      group: root
      mode: 0755
    notify: reload nftables

  - name: Update via apt (mandatory on first run)
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install some usefull packages
    apt:
      state: present
      name:
        - aptitude
        - emacs-nox
        - fail2ban
        - git
        - htop
        - ncdu
        - ntp
        - python3
        - python3-dev
        - python3-pip
        - python3-setuptools
        - python3-venv
        - python3-wheel
        - rsync
        - sudo
        - tcpdump
        - vim-nox

  - name: Set some authorized keys
    copy:
      content: "{{ authorized_keys }}"
      dest: /root/.ssh/authorized_keys
      mode: 0600
      owner: root
      group: root

  - name: Ensure mlocate and locate are not installed
    apt:
      name: ["mlocate", "locate"]
      state: absent

  tags: common
